site_name: UnifyBio
site_url: https://unifybio.github.io/
theme:
  name: material
nav:
  - index.md
  - concepts.md
  - Tutorials:
    - tutorials/quickstart.md
  - local-system.md
  - unify-cli.md
  - import-config.md
  - schema.md
  - other-resources.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
